### ISSUE TITLE
Data generator problems

### ISSUE THREAD

**Issue by michalkowalski94** [Borda/keras-yolo3#13]
While using file formatted as for original qqwweee implementation (on which it is working), i got this error.

`W0829 14:36:56.934175 23120 training_generator.py:251] Your dataset iterator ran out of data; interrupting training. Make sure that your iterator can generate at least `steps_per_epoch * epochs` batches (in this case, 115800 batches). You may need touse the repeat() function when building your dataset.
Traceback (most recent call last):
  File "training.py", line 214, in <module>
    _main(**arg_params)
  File "training.py", line 205, in _main
    callbacks=[tb_logging, checkpoint, reduce_lr, early_stopping])
  File "C:\Users\micha\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\Users\micha\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 300, in model_iteration
    aggregator.finalize()
  File "C:\Users\micha\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 111, in finalize
    raise ValueError('Empty training data.')
ValueError: Empty training data.`

**Comment by Borda** [comment]
Could you please provide more details, so it is possible to reproduce your issue? Thx

**Comment by michalkowalski94** [comment]
I would love to
My training annotation file is formatted like this:
`fixed_images\B_3480_1.LEFT_MLO.tif 102,733,406,1037,1
fixed_images\B_3609_1.RIGHT_MLO.tif
fixed_images\A_0498_1.LEFT_MLO.tif
fixed_images\A_2010_1.RIGHT_MLO.tif
fixed_images\A_0261_1.LEFT_MLO.tif
fixed_images\A_0116_1.RIGHT_CC.tif
fixed_images\A_0510_1.RIGHT_MLO.tif
fixed_images\A_1323_1.LEFT_CC.tif 614,701,845,932,1`

While I'm trying to start training like i did with qqwweee's original implementation, only information that i got is that above. I'm fighting with this bug for like 2 hours right now.

**Comment by michalkowalski94** [comment]
[SOLVED]
Data generator is strictly dependent on batch size (even if batch_size for 'head' is set to 0 and epoch are also set to 0, datagen for 'full' is still dependent on 'head' batch size

**Comment by Borda** [comment]
erll it should not be depending on the unused variable, I ll check it...

**Comment by Borda** [comment]
It should be fixed now, pls, feel free to and any other issue you find... or reopen this one :)
