### ISSUE TITLE
predict not working

### ISSUE THREAD

**Issue by Teque5** [Borda/keras-yolo3#2]
Thanks a lot for this refactor, it's a million times better than the base repo. Having said that, if I train my model with non 416x416 images, predict is later unable to load the model. 

I've tried this **with** and **without** the following changes in `config_train.json`
```python
+    "image-size": [1600, 192],
+    "batch-size": 8,
```
and `train.py`
```python
+    'image-size': (1600, 192),
+    'batch-size': 8,
```

Either way **training works fine**, with xval_loss as low as 25. But when using predict I always get no matter my attempted fixes in `yolo3/yolo.py` on `self.yolo_model.load_weights(self.weights_path)`:
```bash
Traceback (most recent call last):
  File "/xx/yolo3/yolo.py", line 73, in generate
    self.yolo_model = load_model(self.weights_path, compile=False)
  File "/zz/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/zz/keras/engine/saving.py", line 221, in _deserialize_model
    model_config = f['model_config']
  File "/zz/keras/utils/io_utils.py", line 302, in __getitem__
    raise ValueError('Cannot create group in read only mode.')
ValueError: Cannot create group in read only mode.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/zz/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 1 and 42. Shapes are [1,1,1024,255] and [42,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [42,1024,1,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/predict.py", line 176, in <module>
    _main(**arg_params)
  File "scripts/predict.py", line 153, in _main
    classes_path=path_classes, gpu_num=gpu_num)
  File "/xx/yolo3/yolo.py", line 59, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/xx/yolo3/yolo.py", line 86, in generate
    self.yolo_model.load_weights(self.weights_path)
  File "/zz/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/zz/keras/engine/saving.py", line 1058, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/zz/keras/backend/tensorflow_backend.py", line 2465, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/zz/tensorflow/python/ops/variables.py", line 1762, in assign
    name=name)
  File "/zz/tensorflow/python/ops/state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "/zz/tensorflow/python/ops/gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "/zz/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/zz/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/zz/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/zz/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/zz/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 42. Shapes are [1,1,1024,255] and [42,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [42,1024,1,1].
```
Are you sure that predict works as you expect?

_The only time it works for me is if it load the default yolo3.h5 model._

**Comment by Teque5** [comment]
I should mention I have custom classes, anchors, and annotations - but I am extremely confident that I've created those files correctly. I have the same # of classes and # of anchors as base yolo3.

**Comment by Borda** [comment]
well I dd not come so far with the refactoring, and I had to freeze this work some time ago... I am not sure when I could come back to this repo... but any advice or help is welcome :]
unfortunately the original repo looks also quite dead as I opened PR a half year ago and nothing happened since then :/

**Comment by Borda** [comment]
just running the training on tiny-yolo it seems that the dimension confusion is somewhere deeper:
```
INFO:root:Create YOLOv3 (factor: 3) model with 9 anchors and 10 classes.
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer conv2d_1 due to mismatch in shape ((3, 3, 3, 32) vs (16, 3, 3, 3)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer batch_normalization_1 due to mismatch in shape ((32,) vs (16,)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer conv2d_2 due to mismatch in shape ((3, 3, 32, 64) vs (32, 16, 3, 3)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer batch_normalization_2 due to mismatch in shape ((64,) vs (32,)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer conv2d_3 due to mismatch in shape ((1, 1, 64, 32) vs (64, 32, 3, 3)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer batch_normalization_3 due to mismatch in shape ((32,) vs (64,)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer conv2d_4 due to mismatch in shape ((3, 3, 32, 64) vs (128, 64, 3, 3)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer batch_normalization_4 due to mismatch in shape ((64,) vs (128,)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer conv2d_5 due to mismatch in shape ((3, 3, 64, 128) vs (256, 128, 3, 3)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer batch_normalization_5 due to mismatch in shape ((128,) vs (256,)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer conv2d_6 due to mismatch in shape ((1, 1, 128, 64) vs (512, 256, 3, 3)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer batch_normalization_6 due to mismatch in shape ((64,) vs (512,)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer conv2d_7 due to mismatch in shape ((3, 3, 64, 128) vs (1024, 512, 3, 3)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer batch_normalization_7 due to mismatch in shape ((128,) vs (1024,)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer conv2d_8 due to mismatch in shape ((1, 1, 128, 64) vs (256, 1024, 1, 1)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer batch_normalization_8 due to mismatch in shape ((64,) vs (256,)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer batch_normalization_10 due to mismatch in shape ((256,) vs (128,)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer conv2d_9 due to mismatch in shape ((3, 3, 64, 128) vs (512, 256, 3, 3)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer conv2d_12 due to mismatch in shape ((3, 3, 128, 256) vs (256, 384, 3, 3)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer batch_normalization_9 due to mismatch in shape ((128,) vs (512,)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1140: UserWarning: Skipping loading of weights for layer batch_normalization_11 due to mismatch in shape ((128,) vs (256,)).
  weight_values[i].shape))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1121: UserWarning: Skipping loading of weights for layer conv2d_10 due to mismatch in number of weights (1 vs 2).
  len(symbolic_weights), len(weight_values)))
/home/jb/.local/lib/python3.6/site-packages/keras/engine/saving.py:1121: UserWarning: Skipping loading of weights for layer conv2d_13 due to mismatch in number of weights (1 vs 2).
```

**Comment by Borda** [comment]
see also https://github.com/qqwweee/keras-yolo3/issues/417

**Comment by KeKsBoTer** [comment]
I had the same issue and solved it by adding the argument `skip_mismatch=True` to load_weights in yolo.py: 
```python
self.yolo_model.load_weights(self.model_path,by_name=True, skip_mismatch=True)
```

**Comment by Borda** [comment]
Thx, that I have changed, but then there is some issue with Yolo head... Still working on it =)

**Comment by Borda** [comment]
@Teque5 I have been playing around and with this version 25fe475d641ad2946e2f147a5b82a8fd5fc03608 I was able to train model on VOC dataset and later use it for a sample image and video...

**Comment by Borda** [comment]
I have added test training in CricleCI - 5649412c7492d7c42d2ce1b6c0ddb23ffdf2b69e

**Comment by michalkowalski94** [comment]
Checking one thing, I'll be back tomorrow after few epochs

**Comment by michalkowalski94** [comment]
Well to be honest, i have never seen anything like this ever before.
Layers in which dimensions are not compatilbe doesn't exist at all
Model: "model_1"
________________________________________________________________________________________________________________________
Layer (type)                           Output Shape               Param #       Connected to
========================================================================================================================
input_1 (InputLayer)                   [(None, 1632, 1088, 1)]    0
________________________________________________________________________________________________________________________
conv2d (Conv2D)                        (None, 1632, 1088, 16)     144           input_1[0][0]
________________________________________________________________________________________________________________________
batch_normalization (BatchNormalizatio (None, 1632, 1088, 16)     64            conv2d[0][0]
________________________________________________________________________________________________________________________
leaky_re_lu (LeakyReLU)                (None, 1632, 1088, 16)     0             batch_normalization[0][0]
________________________________________________________________________________________________________________________
max_pooling2d (MaxPooling2D)           (None, 816, 544, 16)       0             leaky_re_lu[0][0]
________________________________________________________________________________________________________________________
conv2d_1 (Conv2D)                      (None, 816, 544, 32)       4608          max_pooling2d[0][0]
________________________________________________________________________________________________________________________
batch_normalization_1 (BatchNormalizat (None, 816, 544, 32)       128           conv2d_1[0][0]
________________________________________________________________________________________________________________________
leaky_re_lu_1 (LeakyReLU)              (None, 816, 544, 32)       0             batch_normalization_1[0][0]
________________________________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)         (None, 408, 272, 32)       0             leaky_re_lu_1[0][0]
________________________________________________________________________________________________________________________
conv2d_2 (Conv2D)                      (None, 408, 272, 64)       18432         max_pooling2d_1[0][0]
________________________________________________________________________________________________________________________
batch_normalization_2 (BatchNormalizat (None, 408, 272, 64)       256           conv2d_2[0][0]
________________________________________________________________________________________________________________________
leaky_re_lu_2 (LeakyReLU)              (None, 408, 272, 64)       0             batch_normalization_2[0][0]
________________________________________________________________________________________________________________________
max_pooling2d_2 (MaxPooling2D)         (None, 204, 136, 64)       0             leaky_re_lu_2[0][0]
________________________________________________________________________________________________________________________
conv2d_3 (Conv2D)                      (None, 204, 136, 128)      73728         max_pooling2d_2[0][0]
________________________________________________________________________________________________________________________
batch_normalization_3 (BatchNormalizat (None, 204, 136, 128)      512           conv2d_3[0][0]
________________________________________________________________________________________________________________________
leaky_re_lu_3 (LeakyReLU)              (None, 204, 136, 128)      0             batch_normalization_3[0][0]
________________________________________________________________________________________________________________________
max_pooling2d_3 (MaxPooling2D)         (None, 102, 68, 128)       0             leaky_re_lu_3[0][0]
________________________________________________________________________________________________________________________
conv2d_4 (Conv2D)                      (None, 102, 68, 256)       294912        max_pooling2d_3[0][0]
________________________________________________________________________________________________________________________
batch_normalization_4 (BatchNormalizat (None, 102, 68, 256)       1024          conv2d_4[0][0]
________________________________________________________________________________________________________________________
leaky_re_lu_4 (LeakyReLU)              (None, 102, 68, 256)       0             batch_normalization_4[0][0]
________________________________________________________________________________________________________________________
max_pooling2d_4 (MaxPooling2D)         (None, 51, 34, 256)        0             leaky_re_lu_4[0][0]
________________________________________________________________________________________________________________________
conv2d_5 (Conv2D)                      (None, 51, 34, 512)        1179648       max_pooling2d_4[0][0]
________________________________________________________________________________________________________________________
batch_normalization_5 (BatchNormalizat (None, 51, 34, 512)        2048          conv2d_5[0][0]
________________________________________________________________________________________________________________________
leaky_re_lu_5 (LeakyReLU)              (None, 51, 34, 512)        0             batch_normalization_5[0][0]
________________________________________________________________________________________________________________________
max_pooling2d_5 (MaxPooling2D)         (None, 51, 34, 512)        0             leaky_re_lu_5[0][0]
________________________________________________________________________________________________________________________
conv2d_6 (Conv2D)                      (None, 51, 34, 1024)       4718592       max_pooling2d_5[0][0]
________________________________________________________________________________________________________________________
batch_normalization_6 (BatchNormalizat (None, 51, 34, 1024)       4096          conv2d_6[0][0]
________________________________________________________________________________________________________________________
leaky_re_lu_6 (LeakyReLU)              (None, 51, 34, 1024)       0             batch_normalization_6[0][0]
________________________________________________________________________________________________________________________
conv2d_7 (Conv2D)                      (None, 51, 34, 256)        262144        leaky_re_lu_6[0][0]
________________________________________________________________________________________________________________________
batch_normalization_7 (BatchNormalizat (None, 51, 34, 256)        1024          conv2d_7[0][0]
________________________________________________________________________________________________________________________
leaky_re_lu_7 (LeakyReLU)              (None, 51, 34, 256)        0             batch_normalization_7[0][0]
________________________________________________________________________________________________________________________
conv2d_10 (Conv2D)                     (None, 51, 34, 128)        32768         leaky_re_lu_7[0][0]
________________________________________________________________________________________________________________________
batch_normalization_9 (BatchNormalizat (None, 51, 34, 128)        512           conv2d_10[0][0]
________________________________________________________________________________________________________________________
leaky_re_lu_9 (LeakyReLU)              (None, 51, 34, 128)        0             batch_normalization_9[0][0]
________________________________________________________________________________________________________________________
up_sampling2d (UpSampling2D)           (None, 102, 68, 128)       0             leaky_re_lu_9[0][0]
________________________________________________________________________________________________________________________
concatenate (Concatenate)              (None, 102, 68, 384)       0             up_sampling2d[0][0]
                                                                                leaky_re_lu_4[0][0]
________________________________________________________________________________________________________________________
conv2d_8 (Conv2D)                      (None, 51, 34, 512)        1179648       leaky_re_lu_7[0][0]
________________________________________________________________________________________________________________________
conv2d_11 (Conv2D)                     (None, 102, 68, 256)       884736        concatenate[0][0]
________________________________________________________________________________________________________________________
batch_normalization_8 (BatchNormalizat (None, 51, 34, 512)        2048          conv2d_8[0][0]
________________________________________________________________________________________________________________________
batch_normalization_10 (BatchNormaliza (None, 102, 68, 256)       1024          conv2d_11[0][0]
________________________________________________________________________________________________________________________
leaky_re_lu_8 (LeakyReLU)              (None, 51, 34, 512)        0             batch_normalization_8[0][0]
________________________________________________________________________________________________________________________
leaky_re_lu_10 (LeakyReLU)             (None, 102, 68, 256)       0             batch_normalization_10[0][0]
________________________________________________________________________________________________________________________
conv2d_9 (Conv2D)                      (None, 51, 34, 24)         12312         leaky_re_lu_8[0][0]
________________________________________________________________________________________________________________________
conv2d_12 (Conv2D)                     (None, 102, 68, 24)        6168          leaky_re_lu_10[0][0]
________________________________________________________________________________________________________________________
input_2 (InputLayer)                   [(None, 51, 34, 3, 8)]     0
________________________________________________________________________________________________________________________
input_3 (InputLayer)                   [(None, 102, 68, 3, 8)]    0
________________________________________________________________________________________________________________________
yolo_loss (Lambda)                     (1,)                       0             conv2d_9[0][0]
                                                                                conv2d_12[0][0]
                                                                                input_2[0][0]
                                                                                input_3[0][0]
========================================================================================================================
Total params: 8,680,576
Trainable params: 8,674,208
Non-trainable params: 6,368
________________________________________________________________________________________________________________________
Traceback (most recent call last):
  File "detection.py", line 175, in <module>
    _main(**arg_params)
  File "detection.py", line 157, in _main
    nb_gpu=nb_gpu)
  File "D:\Publikacja\repaired_yolo\yolo3\yolo.py", line 90, in __init__
    self.boxes, self.scores, self.classes = self._create_model()
  File "D:\Publikacja\repaired_yolo\yolo3\yolo.py", line 128, in _create_model
    model.load_weights("best.h5")
  File "C:\Users\micha\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1424, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 759, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\backend.py", line 3066, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1141, in assign
    self._shape.assert_is_compatible_with(value_tensor.shape)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 1103, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (1, 1, 512, 24) and (21, 512, 1, 1) are incompatible

**Comment by arita89** [comment]
Hello, i am still having this exact issue... how can i fix it?
