### ISSUE TITLE
porting to TF 2.0

### ISSUE THREAD

**Issue by Borda** [Borda/keras-yolo3#21]
Since this Keras implementation is based on TensorFlow, it makes sense to port ti to `tf.keras` in TensorFlow 2.0 or higher. This move may solve the issue with multi-GPU training #20 

https://www.pyimagesearch.com/2019/10/21/keras-vs-tf-keras-whats-the-difference-in-tensorflow-2-0/

**Comment by robisen1** [comment]
I would be interested in helping. That being said does the code not work with TF 1+?

**Comment by Borda** [comment]
well, in fact, it was already done :rabbit:

**Comment by robisen1** [comment]
Sorry I do not understand. Are you saying you already have assistance? Are you staying that the code does work with TF1 and TF2?
Thank you for responding.

**Comment by Borda** [comment]
it shall work now with TF 2.x, can you pls test it?

**Comment by robisen1** [comment]
Yes! I will attempt to tonight or early tomorrow. That being said there is now no support for TF 1 right? Just want to make sure.

**Comment by Borda** [comment]
well not sure if it is back TF 1 compatible... :/

**Comment by robisen1** [comment]
Well then i can test both. Ill make two different conda environments and report back.

**Comment by robisen1** [comment]
Sorry I have no responded. I attempted to run the code but tensorflow but very upset due to the fact I have running cuda 11

In the meantime I am creating new environments with cude 10.1 so that everything will work.

Also.. this code base is very nice.

**Comment by robisen1** [comment]
> well not sure if it is back TF 1 compatible... :/

Would you mind emailing me. I would like to share some initial results from testing.

**Comment by Borda** [comment]
@robisen1 I think that the best way would be to share it here... =)

**Comment by robisen1** [comment]
Ok I will later today. Some of it will be in the form of video showing inference.
