### ISSUE TITLE
Q: IOU by kmeans  so small?

### ISSUE THREAD

**Issue by jwnirvana** [Borda/keras-yolo3#22]
NICE job. But why is iou by kmeans so small (4%)?

**Comment by Borda** [comment]
thx, could you elaborate a bit more what you mean by "iou by kmeans so small (4%)"?

**Comment by jwnirvana** [comment]
in kmeans.py:
logging.info('Accuracy: %f', self.avg_iou(all_boxes, result) * 100)
the avg_iou printed is so small

**Comment by jwnirvana** [comment]
thx for replying me so early!

**Comment by jwnirvana** [comment]
Have you run the scripts/kmeans.py by yourself? How about your result?

**Comment by jwnirvana** [comment]
> thx, could you elaborate a bit more what you mean by "iou by kmeans so small (4%)"?

Have you run the scripts/kmeans.py by yourself? How about your result?

**Comment by jwnirvana** [comment]
> thx, could you elaborate a bit more what you mean by "iou by kmeans so small (4%)"?

in ./scripts/kmeans.py:
logging.info('Accuracy: %f', self.avg_iou(all_boxes, result) * 100)
the avg_iou printed is so small

**Comment by Borda** [comment]
I am afraid that from this information I ma not able to reproduce your issue...
I just finished update of `clustering.py` and for my dataset, it gives me 82%

**Comment by Borda** [comment]
@jwnirvana I believe that it is solved for now, but if you have any further question, feel free to reopen this issue...
