### ISSUE TITLE
Q: Have you run the scripts/kmeans.py by yourself?

### ISSUE THREAD

**Issue by jwnirvana** [Borda/keras-yolo3#23]
Have you run the scripts/kmeans.py by yourself? How about your result?

**Comment by Borda** [comment]
Pls, STOP spamming this repository. If you have any personal question contact me directly.

**Comment by Borda** [comment]
Duplicity to #22

**Comment by jwnirvana** [comment]
Dear Datduonguva,
    I am very glad to know you on https://www.github.com/.. I encounter a problem that confuse me one days. That is the average iou is so small after runing the kmeans.py. The result could be seen in the  attachment. I do not konw whether you run the script. How about your result. Could you please give me some suggestions? Looking forward to your reply. Thank you! 
Best  regards!


 Yours sincerely,
jwnirvana






At 2019-10-30 15:03:03, "Jirka Borovec" <notifications@github.com> wrote:


Pls, STOP spamming this repository. If you have any personal question contact me directly.

**Comment by jwnirvana** [comment]
THX. I have solved that bug


| |
王杰
|
|
邮箱jiewangnirvana@163.com
|

签名由 网易邮箱大师 定制

On 10/31/2019 08:49, 王杰 wrote:


Dear Datduonguva,
    I am very glad to know you on https://www.github.com/.. I encounter a problem that confuse me one days. That is the average iou is so small after runing the kmeans.py. The result could be seen in the  attachment. I do not konw whether you run the script. How about your result. Could you please give me some suggestions? Looking forward to your reply. Thank you! 
Best  regards!


 Yours sincerely,
jwnirvana






At 2019-10-30 15:03:03, "Jirka Borovec" <notifications@github.com> wrote:


Pls, STOP spamming this repository. If you have any personal question contact me directly.

**Comment by Borda** [comment]
So far I see, scripts/kmeans.py is not yet suitable to run...
