### ISSUE TITLE
Path for parameters is missing

### ISSUE THREAD

**Issue by smalldroid** [Borda/keras-yolo3#26]
There are many prams arguments in training, detection and yolo.py. Although i set default values for params but still missing path in trainng.py.

**Comment by Borda** [comment]
Hello, could you be more specific default values have you used and what paths are missing?

**Comment by smalldroid** [comment]
I see this line in terminal. Thank you!
![ảnh](https://user-images.githubusercontent.com/237886/68539090-9a88b780-03b0-11ea-9c0c-38463203ca58.png)

**Comment by Borda** [comment]
You are missing path to file with anchors. I will make it as required argument in next commit... =)
