### ISSUE TITLE
Coustom Model and Coustom Classes

### ISSUE THREAD

**Issue by Daniel-1597** [Borda/keras-yolo3#28]
This is the error I am facing while testing it on different weights and different anchors and different classes. How to resolve this issue?
![Screenshot from 2019-11-18 10-54-33](https://user-images.githubusercontent.com/53418529/69026736-22df0c00-09f2-11ea-8569-d879e72ca4c9.png)

**Comment by Borda** [comment]
Hello, could you please copy-paste full error message (not an image) together with some description of your dataset and your usage (what script and parameters you used). Thx

**Comment by Daniel-1597** [comment]
yeah sure sir

**Comment by Daniel-1597** [comment]
Sir, I am using Gaussian Yolo_V3 which uses bdd data set (https://github.com/jwchoi384/Gaussian_YOLOv3) 
**The major issue while converting is that the model is different and the classes are different which are not matching** 

I tried to change  the below line by adding + 12
out_shape = self.yolo_model.layers[-1].output_shape[-1]
            ration_anchors = num_anchors / len(self.yolo_model.output) * (num_classes + 5) + 12 
so that outshape matches when I did this I got the below error

Invalid ArgumentError(see above for trace back): Input to reshape is a tensor with 14592 values, but the requested shape requires a multiple of 11520 [[ Node: Reshape_3 = Reshape[T =DT_FLOAT, Tshape =DT_INT32, _device="/job:localhost/replica :0/task:0/device :CPU:0"](conv2d_59/BiasAdd, Reshape_3/shape)]]
 
Number of Classes = 10

**Comment by Borda** [comment]
Hmmm, are you using [/Gaussian YOLOv3](https://github.com/jwchoi384/Gaussian_YOLOv3) model or just their dataset? For nb of classes, you should not need to do any changes in code... you already have `num_classes` in the line you tried to edit...

**Comment by Daniel-1597** [comment]
I am using their weights file and converting the weights to .h5

**Comment by Borda** [comment]
if you are using their weights, then I believe that it is not compatible and you should ask them... :)

**Comment by Daniel-1597** [comment]
Ok thank you sir
