### ISSUE TITLE
how to generate new anchor box size?

### ISSUE THREAD

**Issue by mnwato** [Borda/keras-yolo3#30]
Hello
How can I generate new anchor box size which exist in "tiny-yolo_anchors.csv" for my own dataset?
thanks

**Comment by Borda** [comment]
sure, you use clustering script on your annotation - [scripts/clustering.py](https://github.com/Borda/keras-yolo3/blob/master/scripts/clustering.py)

**Comment by mnwato** [comment]
> sure, you use clustering script on your annotation - [scripts/clustering.py](https://github.com/Borda/keras-yolo3/blob/master/scripts/clustering.py)

first of all thanks for your support.
I ran this code by the instruction top of that's content but I receive an error :

![photo_2019-12-31_14-05-07](https://user-images.githubusercontent.com/39694920/71618837-9f126500-2bd6-11ea-96e2-7e63039d2648.jpg)

when I add  "--path_anchor" this will going to do training steps, I mean printing layers>>tells how much parameters does it have and starts to calculating from the first epoch and so on.
After this step in which path anchor box sizes will save?

**Comment by Borda** [comment]
there is a typo, you are calling wrong script, it should be:
```bash
python clustering.py \
        --path_dataset ../model_data/VOC_2007_train.txt \
        --path_output ../model_data
```

**Comment by mnwato** [comment]
> there is a typo, you are calling wrong script, it should be:
> 
> ```shell
> python clustering.py \
>         --path_dataset ../model_data/VOC_2007_train.txt \
>         --path_output ../model_data
> ```

I ran this code but receive this error.
![photo_2019-12-31_14-05-07](https://user-images.githubusercontent.com/39694920/71632587-639e8780-2c24-11ea-8d43-4aa1651c2578.jpg)

I created "train.txt" file with this kind of format:
../Dataset/1.jpg 281.0,130.0,128.0,76.0,0
../Dataset/2.jpg 199.0,145.0,312.0,180.0,0

what is the solution?

**Comment by mnwato** [comment]
https://github.com/Borda/keras-yolo3/issues/30#issuecomment-569982421
I appriciate any solution for this error

**Comment by Borda** [comment]
it seems that your boxes are not properly defined as it is required to pass coordinates in top-left and bottom-right corner... see yours boxes widths/heights:
```
array([[-153.,  -54.],
       [ 113.,   35.],
       [  47.,  -77.],
       [-213.,  -10.],
       [ -38.,   24.],
       [ 105.,   15.],
       [  41.,   58.],
       [ 159.,   89.],
       [-142.,  -50.],
       [   2.,   40.]])
```
