### ISSUE TITLE
How to change IOU?

### ISSUE THREAD

**Issue by mnwato** [Borda/keras-yolo3#31]
Hello Borda
I want to change iou .
How can I change this parameter and does this need to train again after changing that?

With respect to your response

**Comment by Borda** [comment]
Hello, you mean change it in training phase? Not sure if there is a paraneter in config for it, but you can change your training script accordingly... =)

**Comment by mnwato** [comment]
I don't know in which phase it can be change. Yes, there is not any parameter in cfg file.
There is a variable called "iou" in yolo.py and training.py but the problem is these are the scripts which runs in training phase, so it means after changing "iou" I must train again and wasting time.
What is your idea to do this changing for iou ? Is there a way to do that quickly?

**Comment by Borda** [comment]
pls, see https://github.com/Borda/keras-yolo3/blob/master/keras_yolo3/yolo.py#L151
